"""Tornado-backed HTTP adaptors.

The transport is optional; install ``hg_cpp[web]`` before importing this
package.
"""

from .http_client_adaptor import (
    Credentials,
    http_client_adaptor,
    http_client_adaptor_impl,
)
from .http_server_adaptor import (
    HttpAdaptorManager,
    HttpDeleteRequest,
    HttpGetRequest,
    HttpHandler,
    HttpPostRequest,
    HttpPutRequest,
    HttpRequest,
    HttpResponse,
    http_server_handler,
    http_server_adaptor,
    http_server_adaptor_impl,
    register_http_server_adaptor,
)
from .websocket_server_adaptor import (
    STR_OR_BYTES,
    WebSocketAdaptorManager,
    WebSocketClientRequest,
    WebSocketConnectRequest,
    WebSocketHandler,
    WebSocketResponse,
    WebSocketServerRequest,
    register_websocket_server_adaptor,
    websocket_server_adaptor,
    websocket_server_handler,
)
from .websocket_client_adaptor import (
    websocket_client_adaptor,
    websocket_client_adaptor_impl,
)
from ._rest_handler import (
    REST_RESPONSE,
    RestCreateRequest,
    RestCreateResponse,
    RestDeleteRequest,
    RestDeleteResponse,
    RestListRequest,
    RestListResponse,
    RestReadRequest,
    RestReadResponse,
    RestRequest,
    RestResponse,
    RestResultEnum,
    RestUpdateRequest,
    RestUpdateResponse,
    rest_handler,
)
from ._rest_client import (
    register_rest_client,
    rest_create,
    rest_delete,
    rest_list,
    rest_read,
    rest_update,
)

__all__ = (
    "Credentials",
    "HttpAdaptorManager",
    "HttpDeleteRequest",
    "HttpGetRequest",
    "HttpHandler",
    "HttpPostRequest",
    "HttpPutRequest",
    "HttpRequest",
    "HttpResponse",
    "http_client_adaptor",
    "http_client_adaptor_impl",
    "http_server_adaptor",
    "http_server_adaptor_impl",
    "http_server_handler",
    "register_http_server_adaptor",
    "REST_RESPONSE",
    "RestCreateRequest",
    "RestCreateResponse",
    "RestDeleteRequest",
    "RestDeleteResponse",
    "RestListRequest",
    "RestListResponse",
    "RestReadRequest",
    "RestReadResponse",
    "RestRequest",
    "RestResponse",
    "RestResultEnum",
    "RestUpdateRequest",
    "RestUpdateResponse",
    "rest_handler",
    "register_rest_client",
    "rest_create",
    "rest_delete",
    "rest_list",
    "rest_read",
    "rest_update",
    "STR_OR_BYTES",
    "WebSocketAdaptorManager",
    "WebSocketClientRequest",
    "WebSocketConnectRequest",
    "WebSocketHandler",
    "WebSocketResponse",
    "WebSocketServerRequest",
    "register_websocket_server_adaptor",
    "websocket_server_adaptor",
    "websocket_server_handler",
    "websocket_client_adaptor",
    "websocket_client_adaptor_impl",
)
